### PR TITLE
Update for 2015

### PR DESCRIPTION
**Pull request by kmdurand**
Updating the viewer so that it will show 2015 shows now

### CODE REVIEW

**Comment by brandonchinn178** [comment]
good to ship!

**Comment by noahsark769** [comment]
@kmdurand are you farmiar with the push process for calchart viewer?

**Comment by kmdurand** [comment]
@noahsark769 Here's what I was thinking of doing: Checkout the github-pages branch, merge with master, grunt build, push to github. Is that correct?

**Comment by noahsark769** [comment]
@kmdurand: not exactly, because you have to edit gitignore. You should read #111 and then follow the instructions: for the commit message, I usually make it "Build for release <version>" as can be seen in [the commit history](https://github.com/calband/calchart-viewer/commits/gh-pages). So this one would be v1.1.0b2

**Comment by noahsark769** [comment]
Also damn, I forgot how sexy and well documented this codebase is. Good job guys

**Pull request merged**
