### PR TITLE
Add autoload audio

### PR DESCRIPTION
**Pull request by brandonchinn178**
Can't test until calband/calchart-server#41

### CODE REVIEW

**Comment by brandonchinn178** [comment]
@allanwlevy good to check

**Comment by kmdurand** [comment]
You may want to talk to the Stud about this one to make sure there's no copyright issues

**Comment by brandonchinn178** [comment]
Already had a talk with ExComm about that. We're in agreement that since we have arranging rights and will only be putting up our midi arrangements, we should be fine, especially since its not on too big of a scale and isnt for profit

**Comment by kmdurand** [comment]
Great!

**Pull request merged**
