### PR TITLE
fix hash on east up movement diagram

### PR DESCRIPTION
**Pull request by brandonchinn178**

### CODE REVIEW

**Comment by noahsark769** [comment]
Can you describe the issue here?

**Comment by brandonchinn178** [comment]
oh sorry. when selecting the movement diagram to be east on top, the hashes didnt move from where they were when west was on top

**Comment by kmdurand** [comment]
I'll go ahead and merge this with the `gh-pages` branch

**Comment by noahsark769** [comment]
Oh I see. Cool!

**Pull request merged**
